### ISSUE TITLE
No 2.1.0 version on geode

### ISSUE THREAD

**Issue by Askar4iklol** [Prevter/GDOpenHack#101]
Prevter, did you added new version of openhack on geode? Because it still says 2.0.1
![image](https://github.com/Prevter/GDOpenHack/assets/129951326/254185b0-034b-497b-8538-bc2cff3f791f)

**Comment by Askar4iklol** [comment]
I downloaded through a github

**Comment by Prevter** [comment]
Geode index doesn't get updates instantly, because mods need to be verified manually by geode devs. It will be there after some time.

**Comment by leinzanne** [comment]
you can always try installing manually from openhack's repository
