### ISSUE TITLE
[Bug] opening chests with free chest hack doesnt save when reopening gd

### ISSUE THREAD

**Issue by Cooldudecrafter** [Prevter/GDOpenHack#106]
**Describe the bug**
when i use the "free chest" hack and i open some chests, i get the items right? well when i close and reopen gd it undoes all the chest opening i did

**To Reproduce**
Use "free chest" to open a chest, close and reopen gd, the chest you opened will now be closed and whatever you got from it will be gone

**Expected behavior**
For me to keep the items that i got from the chest

**Screenshots**

**Comment by Prevter** [comment]
duplicate of #14

**Comment by Cooldudecrafter** [comment]
oh thanks
