### ISSUE TITLE
[Bug] GEODE VERSION i was adding things to the mod with the button (likt the one where you can add noclip accuracy counter ands stuff) and i added something that crashes my game evry time i load it and the only way to stop it was to remove, however when i tried to reinstall it it kept crashing again and i cant use it anymore

### ISSUE THREAD

**Issue by ElectroMuffin** [Prevter/GDOpenHack#109]
**Describe the bug**

**To Reproduce**
What steps did you do to get this result?

**Expected behavior**

**Screenshots**

**Comment by Prevter** [comment]
Probably a corrupted config file, try removing it by pressing `Win+R` and typing:
`%LocalAppData%/GeometryDash/geode/mods/prevter.openhack/`
Then just delete `config.json` and launch the game.

**Comment by Prevter** [comment]
I've already said it's in `%LocalAppData%/GeometryDash/geode/mods/prevter.openhack/`
You've opened the `geode` folder inside your game folder, which is not the same one.

**Comment by ElectroMuffin** [comment]
> I've already said it's in `%LocalAppData%/GeometryDash/geode/mods/prevter.openhack/` You've opened the `geode` folder inside your game folder, which is not the same one.

Thank you! It works now!
