### ISSUE TITLE
Mod Menu not opening

### ISSUE THREAD

**Issue by GDAddict** [Prevter/GDOpenHack#11]
Mod menu looks great and I'm excited for it, but on 2.203, Tab won't open it, and I've pressed every other key. What keybind opens the menu? 
Thanks in advance! :D

**Comment by Prevter** [comment]
I think you might have installed it incorrectly, because everything should work fine on any game version. 

Could you provide a screenshot of your game directory?

**Comment by GDAddict** [comment]
Thanks, I'm pretty sure I installed the Release Zip, but it's working now. No idea what happened, but thanks! :D
