### ISSUE TITLE
no fps below 60

### ISSUE THREAD

**Issue by Askar4iklol** [Prevter/GDOpenHack#112]
when i make my fps lower than 60 then it doesnt work and stays as 60 fps

this was when i firstly installed openhack

wanted to play with low fps

![image](https://github.com/Prevter/GDOpenHack/assets/129951326/4562c715-032f-466d-90ec-ab15da65873c)

**Comment by Kacper8698** [comment]
What if You Enabled Vertical sync in official gd settings?
![Geometry Dash Screenshot 2024 03 17 - 18 02 58 86](https://github.com/Prevter/GDOpenHack/assets/144040477/b923de0c-0819-42ed-9d07-9aff8130b40a)

**Comment by Askar4iklol** [comment]
i did disabled vertical sync but when i make fps LOWER 60 its not working but bigger then 60 works

**Comment by Prevter** [comment]
Works as intended. The only thing I should change is the minimum value of the input box.
FPS Bypass uses in-game settings to make sure it aligns with what RobTops' code does.
Making custom FPS bypass will make the mod incompatible with other mod menus (if you use any), and i plan to keep the mod nonintrusive as much as I can.
