### ISSUE TITLE
keybinds

### ISSUE THREAD

**Issue by battlecatsfan52** [Prevter/GDOpenHack#117]
So, i was thinking, if we could maybe switch the open button from tab to smg else, or add a feature that lets you change it, cuz im bad at coding.

**Comment by Prevter** [comment]
You can inside the "Keybinds" window.

**Comment by battlecatsfan52** [comment]
? how/

**Comment by battlecatsfan52** [comment]
i mean i want to have 2 mod menus at once

**Comment by Prevter** [comment]
![image](https://github.com/Prevter/GDOpenHack/assets/14332428/0d3a3379-6c8e-4b83-add1-54fca2165ad2)
click here and press the key you want the menu to open with
