### ISSUE TITLE
[Question] How do I build Openhack 

### ISSUE THREAD

**Issue by Rustring** [Prevter/GDOpenHack#120]
I noticed some changes (show Hitboxes) and want to build Openhack 

I used the commands and dependencies you mentioned in the building section to build the geode version but I get an error, keep in mind I downloaded the source code through GitHub

**Comment by Prevter** [comment]
you're missing the submodules, try running this command:
```
git submodule update --init --recursive
```

**Comment by Rustring** [comment]
Where to exactly run this?

PS C:\Windows\system32> git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git

**Comment by Prevter** [comment]
> Where to exactly run this?
Inside project root directory.

TODO to myself: Switch to CPM for easier project setup

**Comment by Rustring** [comment]
Here is the file for anyone not wanting to suffer building it was painful windows was installed on a slow HDD
https://www.mediafire.com/file/trfa3p850fr4fvz/prevter.openhack.geode/file

**Comment by Rustring** [comment]
Also I am reopening the issue until the show hitboxes update comes.

**Comment by Prevter** [comment]
closing this, because CI builds are now available, so you can just download build artifacts from there
