### ISSUE TITLE
[Request] allow fps lower 60

### ISSUE THREAD

**Issue by Rommmmaha** [Prevter/GDOpenHack#16]
why not?

**Comment by Prevter** [comment]
It's actually the same as how RobTop implemented it, because I copied some of the code from the game.
I could set it to let's say 10 or 15 fps, but i'm not sure there are a lot of use cases.

**Comment by Prevter** [comment]
Changed minimum number to 30 in https://github.com/Prevter/GDOpenHack/commit/c81dea201a57646b5f492e087f4b5aeea00ccdf9
