### ISSUE TITLE
[Bug] game wont open

### ISSUE THREAD

**Issue by frasgd** [Prevter/GDOpenHack#30]
**Describe the bug**
game doesnt open

**To Reproduce**
no steps just putting the files

**Expected behavior**
idk

**Screenshots**
game doesnt open when putting the openhack files

**Comment by Prevter** [comment]
Need more information. Try opening the game from the exe file and not from Steam. If available, provide "log.txt" file from the game directory.

**Comment by frasgd** [comment]
when i try to open it it gives me the code execution cannot proceed because VCRUNTIME140.DLL was not found and also with MSVCP140.dll

**Comment by frasgd** [comment]
i cant enter the game the game says GeometryDash.exe - System error

The code execution cannot proceed because MSVCP140.dll was not found reinstalling the program may fix this problem 
and

The code executtion cannot proceed because VCRUNTIME140.dll was not found reinstalling the program may fix this
i tried reinstalling the game i searched on google and it says to reinstall microsoft c and nothing worked

**Comment by Prevter** [comment]
You need to update your MSVC Redistributables.
Please download and install this: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by frasgd** [comment]
still i have every version of msvc installed and i still get the same error i dont know what to do at this point
can you try to give me every solution?

**Comment by frasgd** [comment]
i uninstalled the 2015-2022 version i had to download yours but i still get the same error

**Comment by TechStudent10** [comment]
> i uninstalled the 2015-2022 version i had to download yours but i still get the same error

Did you get the game on Steam? Steam automatically downloads the redists for you iirc

**Comment by frasgd** [comment]
> > i uninstalled the 2015-2022 version i had to download yours but i still get the same error
> 
> Did you get the game on Steam? Steam automatically downloads the redists for you iirc

yes i did i even tried uninstalling it

**Comment by frasgd** [comment]
sorry for not responding in a long time cause i kinda gave up on this post after no one commented in a long time

**Comment by frasgd** [comment]
no need for anymore help turns out i had the wrong .NET framework installed thanks for everyone who tried to help
