### ISSUE TITLE
[Question] Is this supported on Linux Mint 21.3 Cinnamon

### ISSUE THREAD

**Issue by geomydas** [Prevter/GDOpenHack#31]
Hello, I have been using this hack before on Windows but after I migrated to Linux Mint, I don't have any idea on how to run or extract this file into the proper folder. For any Linuxers out there, I am only a newbie and just installed Linux Mint today

**Comment by Prevter** [comment]
It should support Linux, but you need to add launch options for Geometry Dash on steam:
```WINEDLLOVERRIDES="xinput9_1_0=n,b" %command%```
Then just make sure you placed all mod files in the game directory.
