### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Chrislaive** [Prevter/GDOpenHack#37]
**Describe the bug**
The menu does not work (Opened the game and pressed Tab and saw nothing)

**To Reproduce**
I took the files from the .zip file and threw it in the Local Files of GD. The files were uploaded but the menu didnt work

**Expected behavior**
When I opened Tab I would see the menu

**Screenshots**
![image](https://github.com/Prevter/GDOpenHack/assets/157902200/83789598-e621-4a58-b82e-065edee9c6f6)

**Comment by Prevter** [comment]
You have downloaded the source code, which is not what you want.
Download this: https://github.com/Prevter/GDOpenHack/releases/download/1.6.0/OpenHack_1.6.0.zip

**Comment by Chrislaive** [comment]
Thank you! :)
