### ISSUE TITLE
[Bug] Geode build crashes after game restart

### ISSUE THREAD

**Issue by ChyppitauCoder** [Prevter/GDOpenHack#42]
why when I install OpenHack in geode, when I restart game, he instantly crash with crashlog: 2024-01-28T09:04:31+0300
Whoopsies! An unhandled exception has occured.

== Geode Information ==
Loader Version: v2.0.0-beta.11
Loader Commit: 231a7c2
Bindings Commit: eb61557
Installed mods: 2
Problems: 1

== Exception Information ==
Faulty Module: C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 6E9B3D4B (CoreUIComponents.dll + 1f3d4b (MinUserRequestViewHitTest + 616859))
Number Parameters: 2

== Stack Trace ==
 
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll + 1f3d4b (MinUserRequestViewHitTest + 616859)
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 12c076
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 47835
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 472d3
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 1215a7
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 5b13e
N:диск 2игры\Geometry Dash v2.204\libcocos2d.dll + c4b1a (cocos2d::CCApplication::run + 26)
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 3c12d8
N:диск 2игры\Geometry Dash v2.204\Geode.dll + c5976 (gdMainHook + 406 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:58)
N:диск 2игры\Geometry Dash v2.204\GeometryDash.exe + 3c267e
C:\WINDOWS\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
C:\WINDOWS\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
C:\WINDOWS\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 6e9b3d4b
EBX: 6f7fee0e
ECX: 00000002
EDX: 00000000
EBP: 015ffa5c
ESP: 015ff910
EDI: 065c3930
ESI: 00000006
EIP: 6e9b3d4b

== Installed Mods ==
~ | [v1.6.0] prevter.openhack
x | [v2.0.0-beta.11] geode.loader. Why?

**Comment by ShawarmaKing7** [comment]
it doesnt work on geode

**Comment by ShawarmaKing7** [comment]
it is still in beta

**Comment by Prevter** [comment]
According to a person from the discord server, this happens because of enabled Discord RPC. Specifically only when it loads the settings (meaning after game restart).
Temporary fix is to disable Discord RPC, until a proper fix is added.

**Comment by PmikeGamer** [comment]
still crashes after disabling discord rpc

**Comment by PmikeGamer** [comment]
the crash log is this

2024-01-29T22:51:24-0600
Whoopsies! An unhandled exception has occured.

== Geode Information ==
Loader Version: v2.0.0-beta.12
Loader Commit: 9cb3cf1
Bindings Commit: a684cc0
Installed mods: 20
Problems: 1

== Exception Information ==
Faulty Module: F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 50C78D0F (50C78D0F)
Number Parameters: 2

== Stack Trace ==
 - 50C78D0F
 - 00DA2357
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 1e4e6
 - 00DA2357
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 1e506
 - 00DA2357
 - 00DA2357
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\GeometryDash.exe + 3c12d8
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\Geode.dll + c6596 (geode::utils::web::AsyncWebRequest::userAgent + 9542)
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 50c78d0f
EBX: 00000016
ECX: 00000005
EDX: 00000003
EBP: 010ff7c0
ESP: 010ff3dc
EDI: fde367eb
ESI: 031be080
EIP: 50c78d0f

== Installed Mods ==
~ | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] b1rtek.gddlintegration
  | [v1.0.4] beat.click-sound
~ | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.1] capeling.icon_profile_2.2
  | [v2.0.0] colon.gd_in_2019
~ | [v4.0.0-alpha.9] cvolton.betterinfo
x | [v1.2.2] firee.PrismMenu
x | [v2.2.0] fleym.nongd
x | [v1.2.14] gdutilsdevs.gdutils
  | [v1.2.4] geode.custom-keybinds
x | [v2.0.0-beta.12] geode.loader
~ | [v1.1.4] geode.node-ids
x | [v1.5.0] geode.texture-loader
~ | [v1.1.3] mat.circle-tool
~ | [v1.6.1] prevter.openhack
~ | [v1.1.4] shineua.minecraft_splash
~ | [v1.0.0] thesillydoggo.entersearch
~ | [v2.1.0] TheSillyDoggo.GradientPages
~ | [v1.1.0] zilko.xdbot
2024-01-29T22:51:24-0600
Whoopsies! An unhandled exception has occured.

== Geode Information ==
Loader Version: v2.0.0-beta.12
Loader Commit: 9cb3cf1
Bindings Commit: a684cc0
Installed mods: 20
Problems: 1

== Exception Information ==
Faulty Module: F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 50C72C75 (50C72C75)
Number Parameters: 2

== Stack Trace ==
 - 50C72C75
 - 25AF044B
 - C:\WINDOWS\System32\USER32.dll + 4120b
 - C:\WINDOWS\System32\USER32.dll + 381ca
 - C:\WINDOWS\System32\USER32.dll + 37897
 - C:\WINDOWS\System32\USER32.dll + 35a3b
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 4696f
 - C:\WINDOWS\System32\USER32.dll + 4120b
 - C:\WINDOWS\System32\USER32.dll + 381ca
 - C:\WINDOWS\System32\USER32.dll + 37dba
 - C:\WINDOWS\System32\USER32.dll + 3b98f
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 7508d
 - C:\WINDOWS\System32\USER32.dll + 4120b
 - C:\WINDOWS\System32\USER32.dll + 349be
 - C:\WINDOWS\System32\USER32.dll + 340b0
 - C:\WINDOWS\System32\USER32.dll + 33ed5
 - C:\WINDOWS\System32\USER32.dll + 4120b
 - C:\WINDOWS\System32\USER32.dll + 381ca
 - C:\WINDOWS\System32\USER32.dll + 37dba
 - C:\WINDOWS\System32\USER32.dll + 3b98f
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 7508d
 - C:\WINDOWS\System32\USER32.dll + 2f186
 - C:\WINDOWS\System32\USER32.dll + 24a01
 - C:\WINDOWS\System32\USER32.dll + 81f2b
 - C:\WINDOWS\System32\USER32.dll + 80cc1
 - C:\WINDOWS\System32\USER32.dll + 81787
 - C:\WINDOWS\System32\USER32.dll + 815be
 - C:\WINDOWS\System32\USER32.dll + 812d5
 - F:\SteamLibrary\steamapps\common\Geometry Dash 2.2 geode\Geode.dll + f6060
 - C:\WINDOWS\System32\KERNELBASE.dll + 1e2942
 - C:\WINDOWS\SYSTEM32\ntdll.dll + a482e
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 67c3e

== Register States ==
EAX: 50c72c75
EBX: 53e78230
ECX: 00000002
EDX: 00000000
EBP: 010fe0c4
ESP: 010fe060
EDI: 0de394a8
ESI: 00000000
EIP: 50c72c75

== Installed Mods ==
~ | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] b1rtek.gddlintegration
  | [v1.0.4] beat.click-sound
~ | [v1.1.0] capeling.goodbye_unnecessary_buttons
x | [v1.1.1] capeling.icon_profile_2.2
  | [v2.0.0] colon.gd_in_2019
~ | [v4.0.0-alpha.9] cvolton.betterinfo
x | [v1.2.2] firee.PrismMenu
x | [v2.2.0] fleym.nongd
x | [v1.2.14] gdutilsdevs.gdutils
  | [v1.2.4] geode.custom-keybinds
x | [v2.0.0-beta.12] geode.loader
~ | [v1.1.4] geode.node-ids
x | [v1.5.0] geode.texture-loader
~ | [v1.1.3] mat.circle-tool
~ | [v1.6.1] prevter.openhack
~ | [v1.1.4] shineua.minecraft_splash
~ | [v1.0.0] thesillydoggo.entersearch
~ | [v2.1.0] TheSillyDoggo.GradientPages
~ | [v1.1.0] zilko.xdbot

i fully uninstalled discord rpc

**Comment by aquakenzie** [comment]
worked for me until i updated NodeIDs to v1.2.3
log:  [2024-02-05_17-31-36.log](https://github.com/Prevter/GDOpenHack/files/14168526/2024-02-05_17-31-36.log)

**Comment by PmikeGamer** [comment]
Mine was crashing because the right dependencies were missing because i bypassed the uac popup. I solved it by reinstalling geode using admin credentials.
