### ISSUE TITLE
Icon bypass bug

### ISSUE THREAD

**Issue by Artoree** [Prevter/GDOpenHack#47]
**The bug**
When i turn on the "unlock all icons" hack it works completely fine.
If i quit the game all the icons will be reset to the default icons when i return

**It should just save right?**

**Comment by Prevter** [comment]
It's a geode-only build issue for now, because the mod doesn't get loaded before the game does.
Fix would require saving current player icons into memory and restore them on load.

**Comment by Rustring** [comment]
I currently have to use gd mega overlay due to this reason :(
