### ISSUE TITLE
OpenHack Breaks the Editor

### ISSUE THREAD

**Issue by InsomniaGaming** [Prevter/GDOpenHack#51]
**Describe the bug**
After playtesting in the editor, stopping the playtest will not return the bottom editing bar fully unless you quit and reopen the editor. Also related is when you open the pause screen and close it, most of the bottom bar will disappear except for the tabs of blocks.

**Comment by Prevter** [comment]
"Hide UI" in creator tab enabled?

**Comment by InsomniaGaming** [comment]
I can't even tell, now the mod loader doesn't even open when I press Tab. Bug still occurs, though.
