### ISSUE TITLE
[Bug] Restart button moves to top right when having level edit on 

### ISSUE THREAD

**Issue by RealShadow69** [Prevter/GDOpenHack#55]
Whenever you have level edit on the restart button moves to the top right for some reason (I'm also using geode) 
![20240205143502_1](https://github.com/Prevter/GDOpenHack/assets/146490996/9474c0fc-c24e-478b-a491-e50e7e101c9b)

**Comment by Prevter** [comment]
That's an issue with another mod. OpenHack doesn't move the buttons, it only enables the hidden one.
