### ISSUE TITLE
[Bug] Icons not saving [GEODE]

### ISSUE THREAD

**Issue by Ilyaviznitsa** [Prevter/GDOpenHack#63]
**Describe the bug**
I was enabled the icon hack but the icons are not saving but the colors are saves
This is bug was only on geode version

**To Reproduce**
I just enabled this hack

**Comment by Cvolton** [comment]
a fix for this bug would most likely be to add `"early-load": true` into mod.json, as this is required to have the mod loaded before GameStatsManager

**Comment by Ilyaviznitsa** [comment]
It's not works
mod.json ignores the early-load
(i have the latest version of the geode, and i don't know where is to add to make it work)

**Comment by Ilyaviznitsa** [comment]
Issue Closed!
Reason: Can't fix it
