### ISSUE TITLE
[Bug] OpenHack Reset (or not saved hacks and shortcuts issue)

### ISSUE THREAD

**Issue by Ilyaviznitsa** [Prevter/GDOpenHack#76]
**Describe the bug**
So... i was enabled some hacks and added some shortcuts and if i reopen my game, the all hacks are not saving!

**To Reproduce**
I just updated the OpenHack to 1.6.1 (maybe) to 2.0.0, and this happens :(

**Expected behavior**
I expected the all hacks and shortcuts are saved, but unfortunately no.

**Screenshots**
Unfortunately i don't have screenshot.

**Comment by Prevter** [comment]
2.0.0 redefined how settings were saved, so all 1.6.1 settings are unsupported by the new version

**Comment by Ilyaviznitsa** [comment]
@Prevter, i mean the mod menu was resetted, no hacks enabled no shortcuts saved.
So... i just maked video but i can't upload it because size of the video 15MB
Can i send it to email?

**Comment by Prevter** [comment]
You can compress the video to 720p, but as I've said the fact settings got reset after updating to 2.0.0 is normal

**Comment by Ilyaviznitsa** [comment]
What I mean is that when I enabled some hacks, when I restart the game, OpenHack resets. (all hacks are disabled, shortcuts are removed, interface is reset) (Note: I reinstalled OpenHack, reinstalling the mod menu doesn't work)
(And unfortunately, I won’t add a video)

**Comment by Ilyaviznitsa** [comment]
I mean, when I enable some hacks, after restarting the game, OpenHack resets (all the hacks are disabled and the shortcuts are removed). The interface is also reset. (Note: I reinstalled OpenHack, but unfortunately reinstalling the mod menu doesn't work.)

(And unfortunately, I won't be adding a video.)

**Comment by Ilyaviznitsa** [comment]
I reinstalled geode, not works again :(
@Prevter, please help.
