### ISSUE TITLE
[Bug] OpenHack v2 GEProton crashes on launch.

### ISSUE THREAD

**Issue by CallMePudding** [Prevter/GDOpenHack#77]
**Describe the bug**
On launch with Proton GE latest, Geode 21, OpenHack v2, the error
```std::bad_array_new_length("bad array new length")```
occurs. Although this could be another mod issue, I doubt as the stack trace (which I forgot to screenshot, and i think thats what its called) mentions the mod multiple times.

**To Reproduce**
1. Install Ubuntu 22.04 in a VM
2. Install Steam, GEProton Geometry Dash, and, manually, Geode.
3. Install OpenHack.
4. Crash.

(note this was on a GDPS)

**Expected behavior**
Game launches as normal.

**Screenshots**
![image](https://github.com/Prevter/GDOpenHack/assets/131171158/c5a10614-6f4f-4349-9c76-d708038f3fdc)

**Comment by Prevter** [comment]
Should be fixed in https://github.com/Prevter/GDOpenHack/commit/64d63d3909dc7e2e29037b02b30132528c931d00
