### ISSUE TITLE
[Bug] When you enter the game

### ISSUE THREAD

**Issue by ItsDaniFeedy** [Prevter/GDOpenHack#80]
When you enter the game, all the parameters that you configured before launch, they are all reset, although nothing was reset before the v2 update. 
I don't know if that's the way it should be, or if that's it. But I didn't have anything crashed after exiting the game.

Before the Game Quit - 
![Снимок экрана 2024-02-25 222859](https://github.com/Prevter/GDOpenHack/assets/161251844/cc1ea3f6-98e4-4fc8-b0b3-1deb0e240bbf)

After the game enter - 
![Снимок экрана 2024-02-25 223120](https://github.com/Prevter/GDOpenHack/assets/161251844/fc230e1c-b5b6-4c6f-abe8-00a635e42b36)

**Comment by Prevter** [comment]
Settings are saved every time you close the menu / press any keybinds.
So if you quit the game with the menu opened, it won't save the new changes.
