### ISSUE TITLE
[Request] Cheat Indicator

### ISSUE THREAD

**Issue by MetriDeniro** [Prevter/GDOpenHack#82]
**Describe your idea.**
Doing levels and need cheat indicator for the video.

**Examples.**
GDMO (Geometry Dash Mega Overlay)

**Comment by Prevter** [comment]
added in https://github.com/Prevter/GDOpenHack/commit/97819c8e33dcdcbe9f2090512465f4b19b4f3e30
will be available in 2.1.0
