### ISSUE TITLE
[Bug] Geode ModLdr is not loading

### ISSUE THREAD

**Issue by Ezzyqq** [Prevter/GDOpenHack#83]
Geode ModLdr is not loading when i'm pasted OpenHack to my GDPS folder. Fix pls
Try edit xinput, this can help i think
https://drive.google.com/file/d/1uY1hiBbw00JHRtj8qJWnvLwwSzo7Q-oC/view?usp=sharing

**Comment by Prevter** [comment]
You're installing the standalone version. What you probably wanted, was to get the geode version, which you can download from the mod index.
