### ISSUE TITLE
Character Bypass

### ISSUE THREAD

**Issue by silvernull** [Prevter/GDOpenHack#89]
**Describe your idea.**
Was there not already a character type and limit bypass in the pre 2.0 version

**Examples.**
Allows characters such as /-?`~ to be typed in text inputs and the limit on maximum amount of characters input to be disabled.

**Comment by Prevter** [comment]
![image](https://github.com/Prevter/GDOpenHack/assets/14332428/c7bc1e85-16e5-474b-a97e-2daa4e8782cc)
It's still there

**Comment by silvernull** [comment]
My bad
